project:
  type: website
  output-dir: docs
website:
  title: "Beranda"
  navbar:
    left:
      - about.qmd
      - href: https://instagram.com/lingkungan_st.andreas_pwt?igshid=MzMyNGUyNmU2YQ==
        icon: Instagram
        text: Instagram
format:    
  html:
    theme: superhero
    css: styles.css

editor: visual

