project:
  type: website
  output-dir: docs
body-header: | 
  
margin-header: |
  ![](/logoAndreas-1.png)
website:
  title: "Beranda"

  navbar:
    left:
      - href: https://standreas.my.id
        icon: home
        text: Home
      - about.qmd
      - href: https://instagram.com/lingkungan_st.andreas_pwt?igshid=MzMyNGUyNmU2YQ==
        icon: instagram
        text: Instagram
format:    
  html:
    theme: superhero
    css: styles.css

editor: visual

